<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220729070034 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rehabilitaciones DROP FOREIGN KEY FK_92DD3340476F72C4');
        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY FK_B88CF8E5F3D48060');
        $this->addSql('ALTER TABLE informe DROP FOREIGN KEY FK_7E75E1D9F3D48060');
        $this->addSql('ALTER TABLE turnos DROP FOREIGN KEY FK_B8555818F3D48060');
        $this->addSql('ALTER TABLE vacaciones DROP FOREIGN KEY FK_CAA83E94F3D48060');
        $this->addSql('ALTER TABLE rehabilitaciones DROP FOREIGN KEY FK_92DD3340E5B3AD58');
        $this->addSql('ALTER TABLE citas DROP FOREIGN KEY FK_B88CF8E56781FC6C');
        $this->addSql('ALTER TABLE informe DROP FOREIGN KEY FK_7E75E1D96781FC6C');
        $this->addSql('ALTER TABLE facultativos DROP FOREIGN KEY FK_C0A65F2FB9A3FCDC');
        $this->addSql('ALTER TABLE pacientes DROP FOREIGN KEY FK_971B7851B9A3FCDC');
        $this->addSql('DROP TABLE aseguradoras');
        $this->addSql('DROP TABLE citas');
        $this->addSql('DROP TABLE facultativos');
        $this->addSql('DROP TABLE informe');
        $this->addSql('DROP TABLE pacientes');
        $this->addSql('DROP TABLE rehabilitaciones');
        $this->addSql('DROP TABLE turnos');
        $this->addSql('DROP TABLE usuarios');
        $this->addSql('DROP TABLE vacaciones');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE aseguradoras (IDASEGURADORA INT AUTO_INCREMENT NOT NULL, NOMBRE VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, PRIMARY KEY(IDASEGURADORA)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE citas (IDCITA INT AUTO_INCREMENT NOT NULL, IDFACULTATIVO INT DEFAULT NULL, IDPACIENTE INT DEFAULT NULL, FECHA DATE NOT NULL, HORA TIME NOT NULL, DISPONIBLE VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, INDEX IDPACIENTE_CITAS (IDPACIENTE), INDEX IDFACULTATIVO_CITAS (IDFACULTATIVO), PRIMARY KEY(IDCITA)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE facultativos (IDFACULTATIVO INT AUTO_INCREMENT NOT NULL, IDUSUARIO INT DEFAULT NULL, ESPECIALIDAD VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, NOMBRE VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, APELLIDO1 VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, APELLIDO2 VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, TELEFONO INT NOT NULL, MIME VARCHAR(255) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, FOTO BLOB NOT NULL, INDEX IDUSUARIO_FACULTATIVOS (IDUSUARIO), UNIQUE INDEX UNIQ_C0A65F2FB9A3FCDC (IDUSUARIO), PRIMARY KEY(IDFACULTATIVO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE informe (IDINFORME INT AUTO_INCREMENT NOT NULL, IDFACULTATIVO INT DEFAULT NULL, IDPACIENTE INT DEFAULT NULL, FECHA DATE NOT NULL, HORA INT NOT NULL, DETALLE VARCHAR(999) CHARACTER SET utf8 DEFAULT NULL COLLATE `utf8_spanish_ci`, INDEX IDPACIENTE_INFORME (IDPACIENTE), INDEX IDFACULTATIVO_INFORME (IDFACULTATIVO), PRIMARY KEY(IDINFORME)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE pacientes (IDUSUARIO INT DEFAULT NULL, IDPACIENTE INT AUTO_INCREMENT NOT NULL, NOMBRE VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, APELLIDO1 VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, APELLIDO2 VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, DIRECCION VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, POBLACION VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, CP INT NOT NULL, PROVINCIA VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, TELEFONO INT NOT NULL, INDEX IDUSUARIO_PACIENTES (IDUSUARIO), UNIQUE INDEX UNIQ_971B7851B9A3FCDC (IDUSUARIO), PRIMARY KEY(IDPACIENTE)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE rehabilitaciones (IDINFORME INT NOT NULL, IDASEGURADORA INT DEFAULT NULL, SESIONESTOTALES INT NOT NULL, SESIONESRESTANTES INT NOT NULL, DETALLE VARCHAR(999) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, INDEX IDASEGURADORA_REHABILITACION (IDASEGURADORA), PRIMARY KEY(IDINFORME)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE turnos (IDFACULTATIVO INT NOT NULL, FECHA DATE NOT NULL, DISPONIBLE VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, HORAINICIO TIME NOT NULL, HORAFIN TIME NOT NULL, INDEX IDX_B8555818F3D48060 (IDFACULTATIVO), PRIMARY KEY(FECHA, IDFACULTATIVO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE usuarios (IDUSUARIO INT AUTO_INCREMENT NOT NULL, EMAIL VARCHAR(45) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, PASSWORD VARCHAR(40) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, TIPOUSUARIO VARCHAR(10) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, UNIQUE INDEX EMAIL (EMAIL), PRIMARY KEY(IDUSUARIO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE vacaciones (IDFACULTATIVO INT NOT NULL, FECHA DATE NOT NULL, VACACIONES VARCHAR(1) CHARACTER SET utf8 NOT NULL COLLATE `utf8_spanish_ci`, INDEX IDX_CAA83E94F3D48060 (IDFACULTATIVO), PRIMARY KEY(FECHA, IDFACULTATIVO)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_spanish_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT FK_B88CF8E5F3D48060 FOREIGN KEY (IDFACULTATIVO) REFERENCES facultativos (IDFACULTATIVO)');
        $this->addSql('ALTER TABLE citas ADD CONSTRAINT FK_B88CF8E56781FC6C FOREIGN KEY (IDPACIENTE) REFERENCES pacientes (IDPACIENTE)');
        $this->addSql('ALTER TABLE facultativos ADD CONSTRAINT FK_C0A65F2FB9A3FCDC FOREIGN KEY (IDUSUARIO) REFERENCES usuarios (IDUSUARIO)');
        $this->addSql('ALTER TABLE informe ADD CONSTRAINT FK_7E75E1D9F3D48060 FOREIGN KEY (IDFACULTATIVO) REFERENCES facultativos (IDFACULTATIVO)');
        $this->addSql('ALTER TABLE informe ADD CONSTRAINT FK_7E75E1D96781FC6C FOREIGN KEY (IDPACIENTE) REFERENCES pacientes (IDPACIENTE)');
        $this->addSql('ALTER TABLE pacientes ADD CONSTRAINT FK_971B7851B9A3FCDC FOREIGN KEY (IDUSUARIO) REFERENCES usuarios (IDUSUARIO)');
        $this->addSql('ALTER TABLE rehabilitaciones ADD CONSTRAINT FK_92DD3340476F72C4 FOREIGN KEY (IDASEGURADORA) REFERENCES aseguradoras (IDASEGURADORA)');
        $this->addSql('ALTER TABLE rehabilitaciones ADD CONSTRAINT FK_92DD3340E5B3AD58 FOREIGN KEY (IDINFORME) REFERENCES informe (IDINFORME)');
        $this->addSql('ALTER TABLE turnos ADD CONSTRAINT FK_B8555818F3D48060 FOREIGN KEY (IDFACULTATIVO) REFERENCES facultativos (IDFACULTATIVO)');
        $this->addSql('ALTER TABLE vacaciones ADD CONSTRAINT FK_CAA83E94F3D48060 FOREIGN KEY (IDFACULTATIVO) REFERENCES facultativos (IDFACULTATIVO)');
    }
}
